name: Deploy to Firebase Hosting on merge

on:
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              working-directory: ./client
              run: npm ci

            - name: Build Angular app
              working-directory: ./client
              run: npm run build

            - name: Deploy to Firebase Hosting
              uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BABY_TRACKER_7CAA1 }}
                  channelId: live
                  projectId: baby-tracker-7caa1
                  entryPoint: ./client
