name: Deploy to Firebase Hosting on merge
on:
    push:
        branches:
            - main

jobs:
    build_and_deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install dependencies
              working-directory: ./client
              run: npm ci

            - name: Generate environment file
              working-directory: ./client
              env:
                  FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
                  FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
                  FIREBASE_DATABASE_URL: ${{ secrets.FIREBASE_DATABASE_URL }}
                  FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
                  FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
                  FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
                  FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
              run: |
                  echo "export const environment = {
                      apiKey: '${FIREBASE_API_KEY}',
                      authDomain: '${FIREBASE_AUTH_DOMAIN}',
                      databaseURL: '${FIREBASE_DATABASE_URL}',
                      projectId: '${FIREBASE_PROJECT_ID}',
                      storageBucket: '${FIREBASE_STORAGE_BUCKET}',
                      messagingSenderId: '${FIREBASE_MESSAGING_SENDER_ID}',
                      appId: '${FIREBASE_APP_ID}'
                  };" > ./src/app/core/firebase/firebase.config.ts

            - name: Build Angular app
              working-directory: ./client
              run: npm run build

            - uses: FirebaseExtended/action-hosting-deploy@v0
              with:
                  repoToken: ${{ secrets.GITHUB_TOKEN }}
                  firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_BABY_TRACKER_7CAA1 }}
                  channelId: live
                  projectId: baby-tracker-7caa1
